[toolchain]
package_manager = "yarn"
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
meridian_protocol = "3hkm2XE7Zfwdv8sBK5oo4acQ6XdM4ypCm6ey68T4i9rN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/allen08/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 60000

[test.validator]
url = "https://api.devnet.solana.com"
bind_address = "127.0.0.1"


[[test.validator.clone]]
address = "CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d"
